// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgsuhlfwhhhlywqpbyuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtnc3VobGZ3aGhobHl3cXBieXVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5OTU1NzUsImV4cCI6MjA2MjU3MTU3NX0.ridpNsm3koiEnQJb5dL5GgQewJr1_iRGZNwMLhRpDYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);